config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :posts, only: %w[index new create show] do
    member do 
      get :upvote
      get :unvote
    end
  end

  resources :comments, only: %w[new create show] do
    member do 
      get :upvote
      get :unvote
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :comment, class_name: 'Comment', optional: true
  belongs_to :user
  has_many :sub_comments, -> { order(points: :desc) }, class_name: 'Comment', foreign_key: 'comment_id'
  has_many :comment_votes

  def voted_points
    comment_votes.count
  end

  def hour_past
    ((Time.now - created_at) / 1.hour).round
  end
end

app/models/comment_vote.rb
class CommentVote < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/post.rb
class Post < ApplicationRecord
  default_scope { order(points: :desc) }
  belongs_to :user

  has_many :post_upvotes
  paginates_per 10
  has_many :comments

  def voted_points
    post_upvotes.count
  end

  # def points
  #   # let's say G = 1.8 
  #   self.points = (voted_points - 1) / (hour_past + 2) ** 1.8
  #   self.save
  # end

  def hour_past
    ((Time.now - created_at) / 1.hour).round
  end

  def comments_count
    comments.count
  end
end

app/models/post_upvote.rb
class PostUpvote < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  has_many :post_upvotes
  has_many :comment_votes
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: %w[create]
  before_action :set_comment, only: %w[upvote unvote show]
  before_action :authenticate_user!, only: %w[create upvote unvote]

  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      flash[:success] = "New post is created successfully."
    end

    redirect_to post_url(comment_params[:post_id])
  end

  def show
    @sub_comments = @comment.sub_comments
    @post = @comment.post
    @new_comment = Comment.new
  end

  def upvote
    if vote_exists?
      redirect_to redirect_str
      return
    end
    
    new_vote = current_user.comment_votes.new
    new_vote.comment = @comment

    if new_vote.save
      flash[:success] = "Comment is upvoted successfully."
    end
    
    redirect_to redirect_str
  end

  def unvote
    if !vote_exists?
      redirect_to redirect_str
      return
    end

    vote = current_user.comment_votes.where(comment_id: @comment.id).first

    if vote.present? && vote.delete
      flash[:success] = "Comment is unvoted successfully."
    end
    
    redirect_to redirect_str
  end

  private

  def set_post
    @post ||= Post.find_by(id: comment_params[:post_id])
  end

  def set_comment
    @comment ||= Comment.find_by(id: params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id, :level, :comment_id)
  end

  def vote_exists?
    @comment.comment_votes.exists?(user_id: current_user.id)
  end

  def redirect_str
    "/posts/#{@comment.post.id}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %w[show upvote unvote]
  before_action :authenticate_user!, only: %w[new create upvote unvote]

  def new
    @post = Post.new
  end

  def show
    @comments = @post.comments.where('comment_id IS NULL')
    @new_comment = Comment.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:success] = "New post is created successfully."
      redirect_to '/'
    else
      render :new
    end
  end

  def upvote
    if vote_exists?
      redirect_to redirect_str
      return
    end
    
    new_vote = current_user.post_upvotes.new
    new_vote.post = @post 

    if new_vote.save
      flash[:success] = "Post is upvoted successfully."
    end
    
    redirect_to redirect_str
  end

  def unvote
    if !vote_exists?
      redirect_to redirect_str
      return
    end

    vote = current_user.post_upvotes.where(post_id: @post.id).first

    if vote.present? && vote.delete
      flash[:success] = "Post is unvoted successfully."
    end
    
    redirect_to redirect_str
  end

  private

  def set_post
    @post ||= Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :url, :content)
  end

  def vote_exists?
    @post.post_upvotes.exists?(user_id: current_user.id)
  end

  def redirect_str
    redirect_str = "/welcome/index"
    if params[:page].present?
      redirect_str += "?page=#{params[:page]}"
    end

    redirect_str
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.page params[:page]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<div class="field comment-head" data-turbolinks="false">
  <div class="comment-body">
    <% if current_user.present? && comment.comment_votes.exists?(user_id: current_user.id) %>
      <%= link_to "unvote", "#{unvote_comment_url(comment.id)}" %> 
    <% else %>
      <%= link_to "up", "#{upvote_comment_url(comment.id)}" %> 
    <% end %>
    <%= comment.user.email %> <%= distance_of_time_in_words(Time.now, comment.created_at) %> ago 
    <a href="#" class="comment-toggles" id="comment-toggle-<%= comment.id %>" onclick="toggleComment(<%= comment.id %>)">[-]</a> 
    <a href="#" class="comment-toggles-collapsed collapsed-comment" id="comment-toggle-collapsed-<%= comment.id %>" onclick="toggleComment(<%= comment.id %>)">[+]</a><br>
    <div class="comment-content" id="comment-content-<%= comment.id %>">
      <%= comment.content %> <br>

      <%= link_to 'Reply', comment_url(comment.id) unless comment.level == 8 %>

      <div style="margin-left: 40px">
        <%= render comment.sub_comments if comment.sub_comments.any? %>
      </div>
    </div>
  </div>
</div>

<% if comment.comment_id.nil? %>
  <hr>
<% end %>

app/views/comments/show.html.erb
<h1><%= link_to 'Mini Hacker News', welcome_index_url %></h1>

<br>

<%= @comment.user.email %> <%= distance_of_time_in_words(Time.now, @comment.created_at) %> ago | on: <%= link_to @post.title, post_url(@post) %><br>
<%= @comment.content %><br>

<%= form_with(model: @new_comment, local: true, url: comments_url, methods: :post) do |f| %>

  <% if @new_comment.errors.any? %>
    <h2><%= pluralize(@new_comment.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% @new_comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>

  <div class="field">
    <%= f.hidden_field :post_id, value: @comment.post_id %>
    <%= f.hidden_field :level, value: @comment.level + 1 %>
    <%= f.hidden_field :comment_id, value: @comment.id %>
    <%= f.text_area :content, size: '50x10' %>
  </div>

  <div class="actions">
    <%= f.submit "Add Comment" %>
  </div>
<% end %>
<br>
<hr>

app/views/layouts/_header.html.erb
<div style="float: right">
  <% if user_signed_in? %>
    <%= current_user.email %>
    <%= link_to 'Logout', destroy_user_session_url, :method=>:delete %> 
  <% else %>
    <%= link_to 'Login / Signup', new_user_session_url %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniHackerNewsClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    
    <%= yield %>
  </body>
</html>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= link_to 'Back', welcome_index_url %>


<%= form_with(model: @post, local: true, url: posts_url, methods: :post) do |f| %>

  <% if @post.errors.any? %>
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>

  

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :content, "text" %><br />
    <%= f.text_area :content, size: '50x10' %>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1><%= link_to 'Mini Hacker News', welcome_index_url %></h1>

<br>

<%= link_to @post.title, @post.url %><br>
<%= @post.content %><br>
<%= @post.voted_points %> points by <%= @post.user.email %> <%= distance_of_time_in_words(Time.now, @post.created_at) %> | <%= @post.comments_count %> comments



<%= form_with(model: @new_comment, local: true, url: comments_url, methods: :post) do |f| %>

  <% if @new_comment.errors.any? %>
    <h2><%= pluralize(@new_comment.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% @new_comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>

  <div class="field">
    <%= f.hidden_field :post_id, value: params[:id] %>
    <%= f.hidden_field :level, value: 1 %>
    <%= f.text_area :content, size: '50x10' %>
  </div>

  <div class="actions">
    <%= f.submit "Add Comment" %>
  </div>
<% end %>
<br>
<hr>

<%= render @comments %>

<%= javascript_pack_tag 'post_show_js' %>

<style>
  .collapsed-comment {
    display: none;
  }
</style>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<% if false %>
  <%- if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %><br />
  <% end %>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %><br />
  <% end %>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<% if false %>
  <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
  <% end %>

  <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
  <% end %>

  <%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
    <% end %>
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<h1>Mini Hacker News</h1>
<%= link_to 'New Post', new_post_url %> <br>
<% @posts.each_with_index do |post, index| %>
  <%= index+1 %>. 

  <% if current_user.present? && post.post_upvotes.exists?(user_id: current_user.id) %>
    <%= link_to "unvote", "#{unvote_post_url(post.id)}?page=#{params[:page]}" %> 
  <% else %>
    <%= link_to "up", "#{upvote_post_url(post.id)}?page=#{params[:page]}" %> 
  <% end %>
  <%= link_to post.title, post.url %><br>
  <%= post.points %> by <%= post.user.email%> <%= distance_of_time_in_words(Time.now, post.created_at) %> ago | <%= link_to "#{post.comments_count} comments", post_url(post.id) %> <br>  

  <hr>

<% end %>


<%= paginate @posts %>